apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: multi-env
  namespace: argocd
spec:
  sourceRepos:
  - 'http://git.younetmedia.com:10080/hungnm/hungnm-test.git'
  destinations:
  - namespace: 'dev'
    server: 'https://kubernetes.default.svc'
  - namespace: 'staging'
    server: 'https://kubernetes.default.svc'
  - namespace: 'production'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
